version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: marketcloud_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketcloud_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - marketcloud_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketcloud_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:root@mysql:3306/marketcloud_db
      PORT: 3000
    command: >
      sh -c "
      npm run build &&
      sleep 10 &&
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run seed &&
      npm run start:prod
      "
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - marketcloud_network

networks:
  marketcloud_network:
    driver: bridge

volumes:
  mysql_data:
